/**
 * Pediatrician-visit PDF report — pure HTML builder (no expo-print import
 * here, so this module stays unit-testable in Node). The screen renders it
 * with expo-print's printToFileAsync and shares the PDF.
 *
 * Privacy contract (CONTEXT.md + ROADMAP-PRD B2): family care data only —
 * private daily check-ins and reflections are NEVER included.
 */
import type { CareEvent, DataExport } from "../data/repository";

function esc(value: string): string {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function fmtDate(d: Date): string {
  return d.toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
}

function fmtTime(d: Date): string {
  return d.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" });
}

/** Events that actually happened on the timeline (growth included). */
function careEvents(data: DataExport): CareEvent[] {
  return data.events.filter((e) => e.type !== "growth");
}

export function buildPediatricReportHTML(data: DataExport): string {
  const events = careEvents(data).slice(0, 14);
  const growth = data.events.filter((e) => e.type === "growth");
  const latestGrowth = (subtype: string) =>
    growth
      .filter((e) => e.subtype === subtype && e.quantity != null)
      .sort((a, b) => b.at.getTime() - a.at.getTime())[0];

  const feedCount = data.events.filter((e) => e.type === "feed").length;
  const diaperCount = data.events.filter((e) => e.type === "diaper").length;
  const sleepEvents = data.events.filter((e) => e.type === "sleep" && e.endAt);
  const sleepHours = sleepEvents.reduce(
    (sum, e) => sum + Math.max(0, (e.endAt!.getTime() - e.at.getTime()) / 3_600_000),
    0,
  );

  const rows = events
    .map(
      (e) => `<tr>
        <td>${fmtDate(e.at)}</td><td>${fmtTime(e.at)}</td>
        <td>${esc(e.subtype)}</td><td>${esc(e.detail ?? "—")}</td><td>${esc(e.by)}</td>
      </tr>`,
    )
    .join("\n");

  const growthRows = (["Weight", "Length", "Head circumference"] as const)
    .map((subtype) => {
      const latest = latestGrowth(subtype);
      if (!latest) return "";
      return `<tr><td>${subtype}</td><td>${esc(latest.detail ?? latest.quantity ?? "—")}</td><td>${fmtDate(latest.at)}</td></tr>`;
    })
    .filter(Boolean)
    .join("\n");

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<style>
  body { font-family: -apple-system, "Segoe UI", Roboto, sans-serif; color: #1d2329; margin: 28px; }
  h1 { font-size: 22px; margin: 0 0 2px; }
  .sub { color: #6b7280; font-size: 13px; margin-bottom: 22px; }
  h2 { font-size: 15px; text-transform: uppercase; letter-spacing: 0.6px; color: #6b7280; margin: 24px 0 8px; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th, td { text-align: left; padding: 7px 8px; border-bottom: 1px solid #e5e7eb; }
  th { color: #6b7280; font-weight: 600; }
  .stat { display: inline-block; margin: 0 26px 6px 0; }
  .stat b { font-size: 20px; display: block; }
  .stat span { font-size: 12px; color: #6b7280; }
  .foot { margin-top: 26px; font-size: 11px; color: #9ca3af; }
</style>
</head>
<body>
  <h1>${esc(data.baby.name || "Baby")} — care summary</h1>
  <div class="sub">Prepared in Alora on ${fmtDate(data.exportedAt)} · ${esc(data.baby.ageLabel)}</div>

  <h2>Overview</h2>
  <div class="stat"><b>${feedCount}</b><span>feeds logged</span></div>
  <div class="stat"><b>${diaperCount}</b><span>diapers logged</span></div>
  <div class="stat"><b>${sleepEvents.length}</b><span>sleeps logged</span></div>
  <div class="stat"><b>${sleepHours.toFixed(1)}h</b><span>sleep in completed naps</span></div>

  <h2>Latest measurements</h2>
  ${growthRows ? `<table><tr><th>Measure</th><th>Value</th><th>Date</th></tr>${growthRows}</table>` : '<p style="font-size:13px;color:#6b7280">No growth measurements logged yet.</p>'}

  <h2>Recent events</h2>
  <table>
    <tr><th>Date</th><th>Time</th><th>Type</th><th>Details</th><th>Logged by</th></tr>
    ${rows}
  </table>

  <div class="foot">
    Generated by Alora from the family’s own logs. Informational summary only — not medical advice.
    Alora · local-first baby care
  </div>
</body>
</html>`;
}
